### ISSUE TITLE
Api not starting in development mode

### ISSUE THREAD

**Issue by Nitwel** [directus/next#582]
When starting the app and api via npm run dev in`/next` i get this error:
```
directus: TypeError: get_config_from_env_1.getConfigFromEnv is not a function
directus:     at E:\Programmieren\Directus\md interface\next\api\src\storage.ts:35:12
directus:     at Array.forEach (<anonymous>)
directus:     at getStorageConfig (E:\Programmieren\Directus\md interface\next\api\src\storage.ts:30:12)
directus:     at Object.<anonymous> (E:\Programmieren\Directus\md interface\next\api\src\storage.ts:17:36)
directus:     at Module._compile (internal/modules/cjs/loader.js:959:30)
directus:     at Module._compile (E:\Programmieren\Directus\md interface\next\node_modules\source-map-support\source-map-support.js:547:25)
directus:     at Module.m._compile (C:\Users\nitwe\AppData\Local\Temp\ts-node-dev-hook-07229285585927858.js:57:33)
directus:     at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
directus:     at require.extensions.<computed> (C:\Users\nitwe\AppData\Local\Temp\ts-node-dev-hook-07229285585927858.js:59:20)
directus:     at Object.nodeDevHook [as .ts] (E:\Programmieren\Directus\md interface\next\node_modules\ts-node-dev\lib\hook.js:63:13)
directus: [ERROR] 09:45:44 TypeError: get_config_from_env_1.getConfigFromEnv is not a function
```

What I did was run `npx lerna clean` go get rid of all node_modules. Then run `npm i` -> `npm run dev`

And after running `npm run dev` for a second time I got:
```
directus: TypeError: Router.use() requires a middleware function but got a Object
directus:     at Function.use (E:\Programmieren\Directus\md interface\next\node_modules\express\lib\router\index.js:458:13)
directus:     at Function.<anonymous> (E:\Programmieren\Directus\md interface\next\node_modules\express\lib\application.js:220:21)
directus:     at Array.forEach (<anonymous>)
directus:     at Function.use (E:\Programmieren\Directus\md interface\next\node_modules\express\lib\application.js:217:7)
directus:     at Object.<anonymous> (E:\Programmieren\Directus\md interface\next\api\src\app.ts:105:5)
directus:     at Module._compile (internal/modules/cjs/loader.js:959:30)
directus:     at Module._compile (E:\Programmieren\Directus\md interface\next\node_modules\source-map-support\source-map-support.js:547:25)
directus:     at Module.m._compile (C:\Users\nitwe\AppData\Local\Temp\ts-node-dev-hook-5859480143249269.js:57:33)
directus:     at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
directus:     at require.extensions.<computed> (C:\Users\nitwe\AppData\Local\Temp\ts-node-dev-hook-5859480143249269.js:59:20)
directus: [ERROR] 09:46:10 TypeError: Router.use() requires a middleware function but got a Object
```

Which continued to pop up each time I tried it again. After going  into `/api` running `npm i` there and then starting only the api it worked.

**Comment by danieljwestman** [comment]
I get the API running in dev (`npm run dev` in /next/api)

But the app won't start (`npm run dev` in /next/app):

 ERROR  Failed to compile with 3 errors                                                  10:12:51

These relative modules were not found:

```
* ./dist/index.json in ../docs/index.js
* ./dist/nav-app.json in ../docs/index.js
* ./dist/nav-web.json in ../docs/index.js
Type checking in progress...
ERROR in /Users/danielwestman/Utveckling/Directus/next/app/src/modules/docs/routes/static.vue(76,4):
76:4 Object is possibly 'undefined'.
    74 | 
    75 | 		onUpdated(() => {
  > 76 | 			view.value.$data.contentEl?.scrollTo({ top: 0 });
       | 			^
    77 | 		});
    78 | 
    79 | 		return { markdown, title, markdownWithoutTitle, view };
Version: typescript 3.9.7
Time: 18640ms
```

**Comment by Nitwel** [comment]
Yep, for me too, I just pushed a fix in https://github.com/directus/next/tree/fix-view-null
You can checkout that branch because I do not have permission to merge that into main.

**Comment by danieljwestman** [comment]
Thanks, I checked out that branch but it still doesn't work.

/next/app/ `npm run dev`

```
ERROR  Failed to compile with 3 errors

These relative modules were not found:

* ./dist/index.json in ../docs/index.js
* ./dist/nav-app.json in ../docs/index.js
* ./dist/nav-web.json in ../docs/index.js
Type checking in progress...
No type errors found
Version: typescript 3.9.7
Time: 17939ms
```

**Comment by Nitwel** [comment]
Oh yea, run `npm run build` inside /next/docs. That should fix it.
And sorry for the inconvenience!

**Comment by danieljwestman** [comment]
`npm run build`

```
> @directus/docs@9.0.0-beta.9 build /Users/danielwestman/Utveckling/Directus/next/docs
> node build.js

internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'directory-tree'
Require stack:
- /Users/danielwestman/Utveckling/Directus/next/docs/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/danielwestman/Utveckling/Directus/next/docs/build.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/danielwestman/Utveckling/Directus/next/docs/build.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @directus/docs@9.0.0-beta.9 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @directus/docs@9.0.0-beta.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielwestman/.npm/_logs/2020-10-08T08_49_16_592Z-debug.log
```

**Comment by Nitwel** [comment]
Okay, this issue I did not have.
I could only think of running `npm i` inside `/next/docs` first but I can't say that this will fix it.

**Comment by danieljwestman** [comment]
I've tried that too, no difference... :(

**Comment by danieljwestman** [comment]
`npm i`

```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> @directus/docs@9.0.0-beta.9 prepublish /Users/danielwestman/Utveckling/Directus/next/docs
> npm run build


> @directus/docs@9.0.0-beta.9 build /Users/danielwestman/Utveckling/Directus/next/docs
> node build.js

internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module 'directory-tree'
Require stack:
- /Users/danielwestman/Utveckling/Directus/next/docs/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/danielwestman/Utveckling/Directus/next/docs/build.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/danielwestman/Utveckling/Directus/next/docs/build.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @directus/docs@9.0.0-beta.9 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @directus/docs@9.0.0-beta.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielwestman/.npm/_logs/2020-10-08T09_06_49_685Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @directus/docs@9.0.0-beta.9 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @directus/docs@9.0.0-beta.9 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danielwestman/.npm/_logs/2020-10-08T09_06_49_721Z-debug.log
```

**Comment by Nitwel** [comment]
Oh, this is related to the @directus/docs package inside node_modules of /next/app
Could you look under `/next/app/node_modules/@directus/docs` and see if a dist folder does exist there.
If not, maybe try running `npm i` in `/next` and `/next/app` again.

**Comment by danieljwestman** [comment]
Now it works!

- [x] /next/ `npm i`
- [x] /next/api `npm i`
- [x] /next/app `npm i`
- [x] /next/docs `npm i`
- [x] /next/ `npm run build`
- [x] /next/api `npm run dev`
- [x] /next/app `npm run dev`

Up'n running!

**Comment by Nitwel** [comment]
Yep, I have to look into that with @rijkvanzanten so it becomes just `npm i` + `npm run dev` in `/next` rather than a whole tour through directus!

**Comment by danieljwestman** [comment]
Ah, nice... now I just need to `npm run build` in /next/

**Comment by rijkvanzanten** [comment]
I've added a `npm run setup` script in the root that effectively does [this](https://github.com/directus/next/issues/582#issuecomment-705445918) under the hood.
