### ISSUE TITLE
Table creation with non default schema on postgres not working

### ISSUE THREAD

**Issue by MiniDigger** [directus/next#865]
not sure if this is an issue in directus or knex, but gotta note down my findings somewhere.

lets start with the error I get:
```
18:02:17 ߚ蠥rror insert into "directus_collections" default values - null value in column "collection" violates not-null constraint
--
  | error: insert into "directus_collections" default values - null value in column "collection" violates not-null constraint
  | at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:280:15)
  | at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
  | at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
  | at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:10:42)
  | at Socket.emit (events.js:315:20)
  | at addChunk (_stream_readable.js:309:12)
  | at readableAddChunk (_stream_readable.js:284:9)
  | at Socket.Readable.push (_stream_readable.js:223:10)
  | at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

that is caused by schema inspector not returning the primary key column here:
https://github.com/directus/next/blob/main/api/src/services/items.ts#L52
because that particular instance of the inspector (why are there so many?) doesn't have my schema set, so it searches in 'public'.

taking one step back, that service (and thus that inspector) is created inside a transaction here:
https://github.com/directus/next/blob/main/api/src/services/collections.ts#L57

its getting passed trx (not this.knex, which would have the schema set), and that doesn't have a schema.

I noticed that this.knex.transaction allows you to pass a config (https://github.com/knex/knex/blob/master/lib/util/make-knex.js#L125) but I am not sure what to pass there, passing this.knex.client.config blew up horrible.

**Comment by rijkvanzanten** [comment]
> (why are there so many?)

Because the schema inspector needs to perform queries within the transaction, otherwise it'll brick up SQLite, where you can only have a single query going at the same time (the transaction itself taking up that query)

**Comment by MiniDigger** [comment]
ah ok, that makes sense.

wasn't an issue in knex, my changes in schema inspector expected a top level knex instance (which has the searhc path additionally in another place), that PR changes it to the proper config object and extends the tests

**Comment by rijkvanzanten** [comment]
Perfect, thanks

**Comment by rijkvanzanten** [comment]
Fixed by https://github.com/knex/knex-schema-inspector/pull/26

**Comment by MiniDigger** [comment]
@rijkvanzanten just a headsup, you forgot to build schema-inspector and including the update in rc6
